### ISSUE TITLE
share button not working?

### ISSUE THREAD

**Issue by SeanAndrew** [wishthis/wishthis#178]
## Branch
On which docker image did you notice this bug?
- [x] stable
- [x] release-candidate
- [x] develop

## Description
Since I'm using the docker image I wanted to put this here first but I'm unsure if this isn't a code/config issue. I did check the code repo and didn't see any issues related to this specifically.

I first noticed this issue when I tried to share out a list in my first setup with the stable image. When I click on the share button for a list nothing happens but checking the browser console I receive this every time I click it

```
Uncaught TypeError: Cannot read properties of undefined (reading 'writeText')
    at HTMLAnchorElement.<anonymous> (wishlists.js?v=6dd2ba86:174:10)
    at HTMLDocument.dispatch (jquery.min.js?v=74425540:2:43336)
    at y.handle (jquery.min.js?v=74425540:2:41320)
(anonymous) @ wishlists.js?v=6dd2ba86:174
dispatch @ jquery.min.js?v=74425540:2
y.handle @ jquery.min.js?v=74425540:2
```

I went ahead and checked both dev and release and noticed the same behavior.

This is the docker compose file I used, I simply swapped out the image tags to test the others.

```
version: '3.7'

services:
  wishthis:
    container_name: wishthis
    restart: unless-stopped
    image: hiob/wishthis:stable
    ports:
    - 8082:80
    volumes:
    - ./config.php:/var/www/html/src/config/config.php
    networks:
    - shared
  mariadb:
    container_name: db
    restart: unless-stopped
    image: mariadb
    volumes:
    - ./db-data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: wishthis
    networks:
    - shared

networks:
  shared:
    name: wishthis
    external: true 
```

It's worth noting that I have not setup a reverse proxy/domain so this is just directly to the docker host via ip and port. I also have not setup [sendmail](https://www.php.net/manual/en/mail.configuration.php) (little green on email management as a whole) which I'm guessing is the culprit? And I only setup an API key for MJML on my stable setup.

Really appreciate the docker image over all, hosting this thing is way better than amazon wish list lol
